/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pdp.practicacafeteria;

import java.rmi.Naming;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author mauro
 */
public class ClienteRemoto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteRemoto.class.getName());
    private ICafeteriaRemota servidor;
    
    
    public ClienteRemoto() {
        initComponents();
        
        setTitle("Paradigmas de Programación - Monitor Remoto");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        iniciarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        btnPausar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtParque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMostradorClientes = new javax.swing.JTextField();
        txtMostradorVendedores = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStockMostradorC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStockMostradorR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCaja = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAreaConsumicion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCocina = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDespensaCocineros = new javax.swing.JTextField();
        txtDespensaVendedores = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtStockDespensaC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtStockDespensaR = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSalaDescanso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRecaudacion = new javax.swing.JTextField();

        jLabel12.setText("Sala de Descanso:");

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPausar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPausar.setText("Pausar / Reanudar");
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarActionPerformed(evt);
            }
        });

        jLabel1.setText("Parque:");

        txtParque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParqueActionPerformed(evt);
            }
        });

        jLabel2.setText("Mostrador:");

        jLabel3.setText("Nº Cafés:");

        jLabel4.setText("Nº Rosquillas:");

        jLabel5.setText("Caja:");

        txtCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCajaActionPerformed(evt);
            }
        });

        jLabel6.setText("Área de Consumición:");

        txtAreaConsumicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaConsumicionActionPerformed(evt);
            }
        });

        jLabel7.setText("Cocina:");

        txtCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCocinaActionPerformed(evt);
            }
        });

        jLabel8.setText("Despensa:");

        jLabel9.setText("Nº Cafés:");

        jLabel10.setText("Nº Rosquillas:");

        jLabel11.setText("Sala de Descanso:");

        txtSalaDescanso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaDescansoActionPerformed(evt);
            }
        });

        jLabel13.setText("Recaudación:");

        txtRecaudacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRecaudacion.setForeground(new java.awt.Color(0, 0, 255));
        txtRecaudacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecaudacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStockDespensaC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStockDespensaR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtStockMostradorC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtStockMostradorR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtParque))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtMostradorClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMostradorVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAreaConsumicion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDespensaCocineros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDespensaVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSalaDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRecaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPausar)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnPausar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtParque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMostradorClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMostradorVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStockMostradorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtStockMostradorR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAreaConsumicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDespensaCocineros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDespensaVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtStockDespensaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtStockDespensaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSalaDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtRecaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void iniciarConexion() {
        try {
            // Conexión RMI
            servidor = (ICafeteriaRemota) Naming.lookup("//localhost/Cafeteria");
            
            // Iniciar el hilo que actualiza los datos cada segundo
            new Thread(() -> loopActualizacion()).start();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error conectando al servidor: " + e.getMessage());
            System.exit(1);
        }
    }
    
    private void loopActualizacion() {
        DecimalFormat df = new DecimalFormat("#,##0.00 €");
        
        while (true) {
            try {
                if (servidor != null) {
                    // Usamos SwingUtilities para no bloquear la pantalla, 
                    SwingUtilities.invokeLater(() -> {
                        try {
                            txtParque.setText(String.valueOf(servidor.obtenerClientesParque()));
                            
                            txtMostradorClientes.setText(String.valueOf(servidor.obtenerClientesMostrador()));
                            txtMostradorVendedores.setText(String.valueOf(servidor.obtenerVendedoresMostrador()));
                            
                            txtStockMostradorC.setText(String.valueOf(servidor.obtenerStockMostradorCafe()));
                            txtStockMostradorR.setText(String.valueOf(servidor.obtenerStockMostradorRosquillas()));
                            
                            txtCaja.setText(String.valueOf(servidor.obtenerClientesCaja()));
                            txtAreaConsumicion.setText(String.valueOf(servidor.obtenerClientesConsumicion()));
                            
                            txtCocina.setText(String.valueOf(servidor.obtenerCocinerosCocina()));
                            
                            txtDespensaCocineros.setText(String.valueOf(servidor.obtenerCocinerosDespensa()));
                            txtDespensaVendedores.setText(String.valueOf(servidor.obtenerVendedoresDespensa()));
                            
                            txtStockDespensaC.setText(String.valueOf(servidor.obtenerStockDespensaCafe()));
                            txtStockDespensaR.setText(String.valueOf(servidor.obtenerStockDespensaRosquillas()));
                            
                            txtSalaDescanso.setText(String.valueOf(servidor.obtenerPersonalDescanso()));
                            
                            txtRecaudacion.setText(df.format(servidor.obtenerRecaudacion()));
                            
                        } catch (Exception ex) {
                            System.err.println("Error al leer datos: " + ex.getMessage());
                        }
                    });
                }
                Thread.sleep(1000); // Esperar 1 segundo
            } catch (Exception e) {
                // Si falla el hilo, esperamos un poco antes de reintentar
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {}
            }
        }
    }
    
    
    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed
        // TODO add your handling code here:
        try {
            if (servidor != null) {
                servidor.pausarOReanudarServidor();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al pausar: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnPausarActionPerformed

    private void txtParqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParqueActionPerformed

    private void txtCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCajaActionPerformed

    private void txtAreaConsumicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaConsumicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaConsumicionActionPerformed

    private void txtCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCocinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCocinaActionPerformed

    private void txtSalaDescansoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaDescansoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaDescansoActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void txtRecaudacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecaudacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecaudacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {}
        
        // Crear y mostrar el cliente remoto
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteRemoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPausar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField txtAreaConsumicion;
    private javax.swing.JTextField txtCaja;
    private javax.swing.JTextField txtCocina;
    private javax.swing.JTextField txtDespensaCocineros;
    private javax.swing.JTextField txtDespensaVendedores;
    private javax.swing.JTextField txtMostradorClientes;
    private javax.swing.JTextField txtMostradorVendedores;
    private javax.swing.JTextField txtParque;
    private javax.swing.JTextField txtRecaudacion;
    private javax.swing.JTextField txtSalaDescanso;
    private javax.swing.JTextField txtStockDespensaC;
    private javax.swing.JTextField txtStockDespensaR;
    private javax.swing.JTextField txtStockMostradorC;
    private javax.swing.JTextField txtStockMostradorR;
    // End of variables declaration//GEN-END:variables
}
