/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pdp.practicacafeteria;

import javax.swing.JFrame;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;
/**
 *
 * @author mauro
 */
public class InterfazCafeteria extends javax.swing.JFrame {

    private boolean pausado = false;
    private final Lock cerrojoPausa = new ReentrantLock();
    private final Condition condPausa = cerrojoPausa.newCondition();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public InterfazCafeteria() {
        // Inicializa los componentes visuales (Código generado por el IDE)
        initComponents();
        
        // Configuraciones extra
        setTitle("Paradigmas de Programación - Simulación Cafetería");
        setSize(1250, 850);
        setLocationRelativeTo(null); // Centrar en pantalla
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPausar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtParque = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEntradaCafeteria = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtEsperandoMostrador = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDespensaCocineros = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDespensaVendedores = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCocina = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMostradorClientes = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtMostradorVendedores = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtEsperandoCaja = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtEnCaja = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtEsperandoConsumir = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtAreaConsumicion = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtSalaDescansoCocineros = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtSalaDescansoVendedores = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        txtDespensaCafes = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtDespensaRosquillas = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtMostradorCafes = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtMostradorRosquillas = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtRecaudacion = new javax.swing.JTextField();

        btnPausar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPausar.setText("Pausar / Reanudar");
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Parque");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Entrada Cafetería");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Esperando Mostrador");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Despensa");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Cocina");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Mostrador");

        txtParque.setColumns(20);
        txtParque.setRows(5);
        jScrollPane1.setViewportView(txtParque);

        txtEntradaCafeteria.setColumns(20);
        txtEntradaCafeteria.setRows(5);
        jScrollPane2.setViewportView(txtEntradaCafeteria);

        txtEsperandoMostrador.setColumns(20);
        txtEsperandoMostrador.setRows(5);
        jScrollPane3.setViewportView(txtEsperandoMostrador);

        txtDespensaCocineros.setColumns(20);
        txtDespensaCocineros.setRows(5);
        jScrollPane6.setViewportView(txtDespensaCocineros);

        txtDespensaVendedores.setColumns(20);
        txtDespensaVendedores.setRows(5);
        jScrollPane7.setViewportView(txtDespensaVendedores);

        txtCocina.setColumns(20);
        txtCocina.setRows(5);
        jScrollPane4.setViewportView(txtCocina);

        txtMostradorClientes.setColumns(20);
        txtMostradorClientes.setRows(5);
        jScrollPane5.setViewportView(txtMostradorClientes);

        txtMostradorVendedores.setColumns(20);
        txtMostradorVendedores.setRows(5);
        jScrollPane8.setViewportView(txtMostradorVendedores);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Mostrador");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Esperando Caja");

        txtEsperandoCaja.setColumns(20);
        txtEsperandoCaja.setRows(5);
        jScrollPane9.setViewportView(txtEsperandoCaja);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Caja");

        txtEnCaja.setColumns(20);
        txtEnCaja.setRows(5);
        jScrollPane10.setViewportView(txtEnCaja);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Esperando para Consumir ");

        txtEsperandoConsumir.setColumns(20);
        txtEsperandoConsumir.setRows(5);
        jScrollPane11.setViewportView(txtEsperandoConsumir);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Área de Consumición");

        txtAreaConsumicion.setColumns(20);
        txtAreaConsumicion.setRows(5);
        jScrollPane12.setViewportView(txtAreaConsumicion);

        txtSalaDescansoCocineros.setColumns(20);
        txtSalaDescansoCocineros.setRows(5);
        jScrollPane13.setViewportView(txtSalaDescansoCocineros);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Sala de Descanso");

        txtSalaDescansoVendedores.setColumns(20);
        txtSalaDescansoVendedores.setRows(5);
        jScrollPane14.setViewportView(txtSalaDescansoVendedores);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Nº Cafés:");

        txtDespensaCafes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDespensaCafesActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Nº Rosquillas:");

        txtDespensaRosquillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDespensaRosquillasActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Nº Cafés:");

        txtMostradorCafes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMostradorCafesActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Nº Rosquillas:");

        txtMostradorRosquillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMostradorRosquillasActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Recaudación");

        txtRecaudacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRecaudacion.setForeground(new java.awt.Color(0, 0, 204));
        txtRecaudacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecaudacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(239, 239, 239)
                                    .addComponent(jLabel28))
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(28, 28, 28)
                                    .addComponent(txtRecaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addComponent(jLabel22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane14))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(273, 273, 273)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(227, 227, 227)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel25))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDespensaCafes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDespensaRosquillas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(373, 373, 373)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMostradorCafes, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(txtMostradorRosquillas))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPausar)
                .addGap(318, 318, 318))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnPausar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel24)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel25))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDespensaCafes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtDespensaRosquillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMostradorCafes)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(txtMostradorRosquillas)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jLabel19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel28))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRecaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel23))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed
        // TODO add your handling code here:
        cambiarEstadoPausa();
    }//GEN-LAST:event_btnPausarActionPerformed

    private void txtDespensaCafesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDespensaCafesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDespensaCafesActionPerformed

    private void txtDespensaRosquillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDespensaRosquillasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDespensaRosquillasActionPerformed

    private void txtMostradorCafesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMostradorCafesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMostradorCafesActionPerformed

    private void txtMostradorRosquillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMostradorRosquillasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMostradorRosquillasActionPerformed

    private void txtRecaudacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecaudacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecaudacionActionPerformed
    
    // Control de Pausa
    public void cambiarEstadoPausa() {
        cerrojoPausa.lock();
        try {
            pausado = !pausado;
            if (pausado) {
                btnPausar.setText("REANUDAR");
            } else {
                btnPausar.setText("Pausar / Reanudar");
                condPausa.signalAll();
            }
        } finally {
            cerrojoPausa.unlock();
        }
    }

    public void comprobarPausa() {
        cerrojoPausa.lock();
        try {
            while (pausado) {
                try {
                    condPausa.await();
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
            }
        } finally {
            cerrojoPausa.unlock();
        }
    }
    
    // Setters
    public void setParque(String s) { txtParque.setText(s); }
    public void setEntradaCafeteria(String s) { txtEntradaCafeteria.setText(s); }
    public void setEsperandoMostrador(String s) { txtEsperandoMostrador.setText(s); }
    public void setEnMostradorClientes(String s) { txtMostradorClientes.setText(s); }
    public void setEsperandoCaja(String s) { txtEsperandoCaja.setText(s); }
    public void setEnCaja(String s) { txtEnCaja.setText(s); }
    public void setRecaudacion(String s) { txtRecaudacion.setText(s); }
    public void setEsperandoConsumir(String s) { txtEsperandoConsumir.setText(s); }
    public void setAreaConsumicion(String s) { txtAreaConsumicion.setText(s); }
    
    public void setSalaDescansoCocineros(String s) { txtSalaDescansoCocineros.setText(s); }
    public void setSalaDescansoVendedores(String s) { txtSalaDescansoVendedores.setText(s); }
    public void setCocina(String s) { txtCocina.setText(s); }
    public void setDespensaCocineros(String s) { txtDespensaCocineros.setText(s); }
    public void setDespensaVendedores(String s) { txtDespensaVendedores.setText(s); }
    public void setDespensaCafes(int n) { txtDespensaCafes.setText(String.valueOf(n)); }
    public void setDespensaRosquillas(int n) { txtDespensaRosquillas.setText(String.valueOf(n)); }
    public void setMostradorVendedores(String s) { txtMostradorVendedores.setText(s); }
    public void setMostradorCafes(int n) { txtMostradorCafes.setText(String.valueOf(n)); }
    public void setMostradorRosquillas(int n) { txtMostradorRosquillas.setText(String.valueOf(n)); }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPausar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea txtAreaConsumicion;
    private javax.swing.JTextArea txtCocina;
    private javax.swing.JTextField txtDespensaCafes;
    private javax.swing.JTextArea txtDespensaCocineros;
    private javax.swing.JTextField txtDespensaRosquillas;
    private javax.swing.JTextArea txtDespensaVendedores;
    private javax.swing.JTextArea txtEnCaja;
    private javax.swing.JTextArea txtEntradaCafeteria;
    private javax.swing.JTextArea txtEsperandoCaja;
    private javax.swing.JTextArea txtEsperandoConsumir;
    private javax.swing.JTextArea txtEsperandoMostrador;
    private javax.swing.JTextField txtMostradorCafes;
    private javax.swing.JTextArea txtMostradorClientes;
    private javax.swing.JTextField txtMostradorRosquillas;
    private javax.swing.JTextArea txtMostradorVendedores;
    private javax.swing.JTextArea txtParque;
    private javax.swing.JTextField txtRecaudacion;
    private javax.swing.JTextArea txtSalaDescansoCocineros;
    private javax.swing.JTextArea txtSalaDescansoVendedores;
    // End of variables declaration//GEN-END:variables
}
